# Setup
title: Zunhao Wei
tagline: Blog
description: >
    Zunhao's blog
url: https://haha454.github.io
baseurl: ''
paginate: 5
permalink: pretty

# About/contact
author:
  name: Zunhao Wei
  email: zunhaowei@gmail.com
  github: https://github.com/haha454

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom vars
version: 1.1.0
google_analytics_id: G-2Y6GHV22MN
